steps:
  # Step 1: Checkout code from Azure DevOps repository
  - checkout: self
    persistCredentials: true

  # Step 2: Set up Git configuration (optional)
  - script: |
      git config --global user.name "slawomirmalyszko"
      git config --global user.email "okok@gmail.com"  
    displayName: 'Set Git Config'

  - script: |
      set -x  # Enable verbose logging
      git remote add github https://$(GITHUB_USERNAME):$(GITHUB_TOKEN)@github.com/$(GITHUB_REPO)
      git fetch origin  # Fetch latest changes from Azure DevOps (origin)

      # Make sure we're on the correct branch (master or main as appropriate for DevOps)
      git checkout master || git checkout -b master  # Checkout master branch from DevOps, create if it doesn't exist
      git status  # Check the current status of the repo
      git log --oneline -5  # Show last 5 commits to verify if there are new commits to push

      git push github --all --force
    displayName: 'Push to GitHub with commit history'

