trigger:
  branches:
    include:
      - "*"  # or any branch you want to sync

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Checkout code from Azure DevOps repository
  - checkout: self
    persistCredentials: true

  # Step 2: Set up Git configuration (optional)
  - script: |
      git config --global user.name "Azure DevOps"
    displayName: 'Set Git Config'

  # Step 3: Push commits to GitHub with history
  - script: |
      git remote add github https://$(GITHUB_USERNAME):$(GITHUB_TOKEN)@$(GITHUB_REPO)
      git push github --all
    displayName: 'Push to GitHub with commit history'

